# Generated by Django 5.0.4 on 2024-05-30 05:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main_app", "0003_alter_test_patient"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patient",
            name="bed",
        ),
    ]
